### Spring ###
spring:
  # Application
  application:
    name: apache-kafka-spring-boot-event-stream-pipeline
  # Profiles
  profiles:
    active: local
  # AOP
  aop:
    proxy-target-class: true
  # JMX
  jmx:
    enabled: false
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
