### APP ###
app:
  # REST
  rest:
    consumer:
      mastodon:
        url: <MASTODON URL>
        bearer-token: <MASTODON BEARER TOKEN>

### Spring ###
spring:
  # Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acntech
    username: acntech
    password: P455w0rd
  # Flyway
  flyway:
    locations:
      - classpath:db/vendor/mysql

### Logging ###
logging:
  # Level
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
