version: "3.7"

services:
  acntech.mysql:
    image: mysql
    container_name: acntech.mysql
    environment:
      MYSQL_USER: acntech
      MYSQL_PASSWORD: P455w0rd
      MYSQL_DATABASE: acntech
      MYSQL_ROOT_PASSWORD: P455w0rd
    command: --lower_case_table_names=1 --log-bin=bin.log --log-bin-index=bin.log.index --binlog_do_db=acntech
    ports:
      - "3306:3306"
    volumes:
      - mysql.conf:/etc/mysql/conf.d
      - mysql.data:/var/lib/mysql
    networks:
      - mysql

volumes:
  mysql.conf:
    name: acntech.mysql.conf
  mysql.data:
    name: acntech.mysql.data

networks:
  mysql:
    name: acntech.mysql
